### ISSUE TITLE
RF přepínač

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#1]
Vypadá to že použitelný by měl být  [PE4259](https://www.psemi.com/pdf/datasheets/pe4259ds.pdf)

Alternativou je ještě tenhle [AS193](https://cz.mouser.com/datasheet/2/472/200186C-1524766.pdf)

**Comment by ChroustJan** [comment]
Zvolíme PE4259. Pin 6 #CTRL dame na Vdd?

**Comment by kaklik** [comment]
> Zvolíme PE4259. Pin 6 #CTRL dame na Vdd?

Myslím že by to mělo být vyvedené na hřebínek, neboť většina těchto přepínačů se ovládá komplementárně. Tenhle je vyjímka, kdybychom to zapojili fixně, tak může být problém s jeho záměnou za jiný typ. 

Navíc ještě to napájecí napětí u toho přepínače může být maximálně 3.3 V ale zesilovač z #3 má napájecí napětí i 5V.
