### ISSUE TITLE
Přidání indikační LED

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#10]
Napadlo mě k signálu OC přidat indikační LED, která by se rozsvítila v případě, že by došlo k poškození zesilovače.  V případě trvalého poškození by zřejmě blikala, protože proudová pojistka se bude snažit o opakované zapnutí.

**Comment by ChroustJan** [comment]
@kaklik  A vidíš  tam prostor jí tam dát? Jakou barvu? A ta dioda by byla proti zemi přes ten pull-up?

**Comment by kaklik** [comment]
Myslim že v téhle oblasti je pro jednu LED prostoru dost.

![image](https://user-images.githubusercontent.com/1194177/98042798-75dce980-1e24-11eb-8334-044b4794bf48.png)


Barva třeba červenou. 

Ten OC je otevřený kolektor. 

![image](https://user-images.githubusercontent.com/1194177/98042875-9b69f300-1e24-11eb-8646-ebf01fdf9e31.png)


Takže tam musí být LED s odporem do napájení.

**Comment by ChroustJan** [comment]
Provedeno.
