### ISSUE TITLE
SAW filtr

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#2]
Pro modul je potřeba najít SAW filtr, který je možné dát na vstupní RX cestu směrem k modulu ISM01A. 
Tím by měla být zvýšena vstupní odolnost modemu.

Vybraný filtr by měl mít stejné pouzdro pro obě základní [ISM pásma 433MHz a  868MHz](https://www.ctu.cz/sites/default/files/obsah/ctu/vseobecne-opravneni-c.vo-r/10/12.2019-9/obrazky/vo-r10-122019-9.pdf). 
Velkou část  thru se SAW filtry do nedávna ovládala firma EPCOS, která byla ale zřejmě koupena firmou TDK a produky EPCOS se nyní staly nedostupné. 

## 433MHz 

- [B39431B3721U410](https://cz.farnell.com/epcos/b39431b3721u410/filter-saw-433-92mhz/dp/2360864) - pouzdro 3.0 x 3.0 x 1.1 mm

Alternativou je [AFS434S3-T](https://cz.farnell.com/abracon/afs434s3-t/saw-filter-434mhz-smd-6/dp/2849519), který však má insertion loss 2.7 - 4.5 dB - pouzdro 3.8 x 3.8 x 1.5mm.

## 868MHz 

- [B39871B3715U410](https://cz.mouser.com/datasheet/2/136/B3715-84099.pdf) - pouzdro 3.0 x 3.0 x 1.1 mm
- [AFS869S3-T](https://cz.farnell.com/abracon/afs869s3-t/filter-saw-869mhz-smd/dp/2467873) - pouzdro 3.8 x 3.8 x 1.5mm

**Comment by ChroustJan** [comment]
@kaklik filtry nemají stejná pouzdra. Jak se bude tento stav řešit na PCB?

**Comment by kaklik** [comment]
Vybrány filtry AFS869S3-T a AFS434S3-T.
