### ISSUE TITLE
Vstupní zesilovač

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#3]
Vhodné
- [SPF5189Z](https://eu.mouser.com/ProductDetail/Qorvo/SPF5189Z?qs=p6lVfQR1GSoxtfscJmmzLQ==)

Lze zapojit podle [modemu z balonu](https://github.com/ODZ-UJF-AV-CR/balon/blob/master/HW/transceiver_M1_1_2016/Modem-Modem.pdf):

![image](https://user-images.githubusercontent.com/1194177/96640434-7012de80-1323-11eb-9dc0-0ae496eea8c3.png)

Ve schéma balonového transceiveru je pro vypínání zesilovače použita [proudová pojistka](https://cz.mouser.com/ProductDetail/Texas-Instruments/TPS22945DCKR?qs=IDSsxkoac0yt8oAd7q17%2FA%3D%3D), která je ovládana pinem transceiveru. 

To není  vůbec špatný nápad, neboť zesilovač je vhodné vypínat, aby při vysílání nemohlo dojít k poškození přijímače. 

V datasheetu píšou něco o možnosti nastavovat pracovní proud, zároveň tam ale nevidím žádné schéma, které by tuhle možnost popisovalo. Je tak možné že proudová pojistka v zapojení modemu balonu ve skutečnosti funguje jako zdroj proudu.  Zesilovač je v tomto případě napájen z 3.3V napájecího napětí.

**Comment by ChroustJan** [comment]
Aplikováno

**Comment by kaklik** [comment]
Teď jsem si všiml, že v tom zapojení je jedna chyba.  Spínač zesilovače nemůže zůstat v nedefinovaném stavu (podle datasheetu je to explicitně zakázáno).

Druhá věc pak je, že ve schéma modemu z balonu se zesilovač ovládá společně s přepínačem. 

![image](https://user-images.githubusercontent.com/1194177/97737422-45701500-1add-11eb-986e-a01c27679511.png)

Na to se v aktuálním schéma nemyslí.  Reálně by to znamenalo, že na modulu bude muset být trvale zpojený drátek mezi  spínačem napájení zesilovače a ovládáním RF přepínače. 

Navrhoval bych hřebínek ON odstranit a tento signál zapojit ke vhodnému vstupu přepínače.

**Comment by ChroustJan** [comment]
@kaklik  mohl by jsi definovat stavy, které tam mají být při nezapojeném modulu? Ideálně i kam se má připojit ON.

**Comment by kaklik** [comment]
Základní neřízený stav by měl být: 

1. Vypnutý vstupní zesilovač - ON  v log 0. 
2. RF Přepínač přepnutý na vysílání

Z toto vyplývá že ON musí být připojen na přepinači na signál, který odpovídá stavu log 0, pro vysílání a stavu log 1 pro příjem. Což je podle [datasheetu](https://www.psemi.com/pdf/datasheets/pe4259ds.pdf) zřejmě signál CTRL na pinu 4. 

RF vstup zesilovače pak také musí být připojen na odpovídající RF výstup, což je RF1.  Změna je poměrně komplikovaná, takže jsem ji rovnou provedl ve schéma. 


Spínač má i tepelnou ochranu. Aby tahle funkce dávala smysl, tak by spínač měl být umístěn v blízkosti zesilovače. (Tepelná ochrana spíná přibližně při 140 deg C).

**Comment by ChroustJan** [comment]
Předělán PCB. Spínač nebylo možné umístit přímo k LNA. Přednost dostala RF část.
