### ISSUE TITLE
Potisk na modulu

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#6]
Aktuální provedení: 

![image](https://user-images.githubusercontent.com/1194177/97580192-47f64000-19f3-11eb-8243-e0e0396884c2.png)

Mě to přijde dost nepřehledné.. Trvá mi celé minuty, abych pochopil, jak je to zhruba plánované. 

Potíž podle mě je v tom, že je tam moc textových popisků.  Situaci by zřejmě názorněji vystihl obrázek dvou přepínačů s odpovídajícími signály. 

Něco třeba na způsob tohoto: 

![image](https://user-images.githubusercontent.com/1194177/97580672-e4b8dd80-19f3-11eb-8ef8-1e747b451582.png)

**Comment by ChroustJan** [comment]
To to tam chceš opravdu kreslit? Vždy se předpokládá, že budeš mít nějaké
znalosti toho modulu. A je to celé malé.

**Comment by kaklik** [comment]
Je to fakt nepřehledný. 
Možná jestli dovedeš ty textové popisky nějak zlepšit, ale tohle myslím skoro nejde používat.

**Comment by ChroustJan** [comment]
@kaklik  https://github.com/mlab-modules/RFSWITCH01/blob/RFSWITCH01A/README.md  případně to uprav do podoby, která se ti líbí.

**Comment by kaklik** [comment]
Ok, tohle je velké zlepšení! :) 

![RFSWITCH01A_top_big](https://user-images.githubusercontent.com/1194177/97735757-093bb500-1adb-11eb-886c-4f490f1022f7.png)

Stejně ale asi ještě zkusím ty přepínače zarovnat a ty funkční bloky nahradit symboly místo nápisů.

**Comment by ChroustJan** [comment]
@kaklik  to bude jedině dobře.

**Comment by kaklik** [comment]
Po dnešní změně zapojení to vypadá že ty přepínače by měly zobrazovat i ten klidový stav, kudy poteče signál bez ovládání řídících signálů.

**Comment by ChroustJan** [comment]
@kaklik  provést dokončení potisku modulu. Vrstvy F.Silksc...

**Comment by kaklik** [comment]
> @kaklik provést dokončení potisku modulu. Vrstvy F.Silksc...

Je nějaký důvod proč tahle napájecí cestá je ve žlutý vrstvě a nemuže být v zelený? 

![image](https://user-images.githubusercontent.com/1194177/97814991-65ddd200-1c8b-11eb-8e47-2416e4855065.png)

**Comment by kaklik** [comment]
Vyřešeno: 

![image](https://user-images.githubusercontent.com/1194177/98038399-6312e680-1e1d-11eb-80a5-debf0001c2c2.png)
