### ISSUE TITLE
Rozložení součástek

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#7]
Úplně se mi nezdá tahle část.

![image](https://user-images.githubusercontent.com/1194177/97581004-555ffa00-19f4-11eb-9cc5-c9c001b8e21c.png)

- cesta mezi L3 k U2 je zbytečně dlouhá. L3 by i mohla být otočená o 90 stupňů, aby byla paralelně s nožičkou U2. 
-  L2 by měla být jednou nožičkou na cestě mezi U2 a filtrem FL1, aby zde nevnikal rezonanční stub.

**Comment by ChroustJan** [comment]
Provedeno
