### ISSUE TITLE
RF layout

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFSWITCH01#8]
Na desce jsem si všiml nepříjemných přechodů tvaru "bočních stěn" mikropáskových vedení. Výrazné je to zejména u konektorů. 

![image](https://user-images.githubusercontent.com/1194177/97582450-0c10aa00-19f6-11eb-83a3-2a7faccd7eb4.png)

Zde by bylo potřeba, aby měď byla vylitá spojitě po obou stranách RF cesty - Ta šířka cesty a izolační mezera je teď nějak napočítaná a vychází to zrovna takhle blbě? 

Dále se taky snažím zjistit, zda KiCAD umí zaoblené cesty - zvýšilo by to kvalitu a odstranilo možnost vzniku odrazů.

**Comment by ChroustJan** [comment]
Provedena optimalizace - řeší jen vylitou zem kolem celých RF cest

**Comment by kaklik** [comment]
@ChroustJan  Víš to, že v tom návrhu jsou použity via s vrtáním 0.15mm?

**Comment by ChroustJan** [comment]
@kaklik  to je nějaký problém?

**Comment by kaklik** [comment]
Je to úplně na hranici vyrobitelnosti. Předpokládám, že to zbytečně zdraží následnou výrobu. 

Zaoblené cesty se v novém KiCADu dělají takhle:

![image](https://user-images.githubusercontent.com/1194177/97711296-35e0d400-1abd-11eb-80c3-ec294869bb04.png)

Menu se otevře po vybrání dvou úseků a volbou "Fillet Tracks" na pop-up menu pravého tlačítka myši.

**Comment by ChroustJan** [comment]
Být 50% nad limitem říkáš na hraně? Kolik by jsi tam dal? Volil jsem to malé, aby se to tam vešlo.

**Comment by kaklik** [comment]
> Být 50% nad limitem říkáš na hraně? Kolik by jsi tam dal? Volil jsem to malé, aby se to tam vešlo.


Co jsem se koukal tak poměrně dost výrobců očekává prokovy 0.6mm a standardní limit (pro desku tloušťky 1.6mm) je tak 0.3mm průměr vrtáku. Takže prokov může být asi o tloušťku prokovení menší.

**Comment by ChroustJan** [comment]
Parametry POOL servisu Gatemy.
![image](https://user-images.githubusercontent.com/9783606/97772291-0f1ab000-1b46-11eb-9c13-508b7e3af466.png)

Teď nevím zda KiCad má výslednou díru, nebo průměr vrtáku. Každopádně si to můžeme pojistit tím že tam dáme tedy 0,2mm a bude to jistota. A minimální průměr toho CU okruží by tedy měl být 0,45. Tohle by mohli být parametry pro zemnící VIA. Ostatní dávám 0,4 a 0,8mm aby jsme měli jistotu.

**Comment by kaklik** [comment]
Ok, průměr vias ale nebyl hlavním předmětem tohoto issue.
Důležitá je ta optimalizace RF layoutu, která souvisí například s tím zaoblením RF cest.

**Comment by kaklik** [comment]
Vyzkoušel jsem si to trochu zlepšit ten layout. Řekl bych že ta správná cesta vypadá nějak takhle: 

![image](https://user-images.githubusercontent.com/1194177/97813499-f535b600-1c88-11eb-9736-806a530ee8a9.png)

Ty pozice součástek a tak, by zřejmě asi chtělo trošku daladit. 

Potíž, na kterou jsem přitom přišel je ale tohle: 

![123245681_387253822480547_680556241535195163_n](https://user-images.githubusercontent.com/1194177/97813567-4e054e80-1c89-11eb-9a85-f6141f4b7a6b.png)


Není mi jasné na základě čeho je zvolena ta součastá šířka RF spojů, která je tam použita.

**Comment by ChroustJan** [comment]
@kaklik  jednou jsem tu cestu spočítal a používám jí všude na 2V. Tenkrát jsme i získávali nějaké informace od našich dodavatelů. Tak jsem to vyhodnotil, jako přesnější výpočet.

**Comment by kaklik** [comment]
Chybí tam ještě via fencig okolo RF cest.

**Comment by ChroustJan** [comment]
Přidány via

**Comment by ChroustJan** [comment]
@kaklik je to hotové?

**Comment by kaklik** [comment]
Teď už si myslím, že je.
