### ISSUE TITLE
Rozložení součástek na PCB

### ISSUE THREAD

**Issue by ChroustJan** [mlab-modules/RFSWITCH01#9]
@kaklik provést kontrolu rozložení součástek na PCB.

**Comment by kaklik** [comment]
Myslím že pozice součástek jsou v principu správně. Jen je asi nepraktické že dvoupinový hřebínek OC je nyní takhle samostatně. chápu že je ale asi složité jej přiřadit k ostatním.

Možná by ale bylo řešení jej prohodit s napájecím hřebínkem. Což by možná bylo i logické protože hlavní odběr na desce je zesilovač. Tudíž by vstup pro napájení měl být poměrně blízko zesilovači.

**Comment by ChroustJan** [comment]
Moc velký zásah do desky.
